import 'package:meta/meta.dart';
import 'package:serverpod/serverpod.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:magic_recipe_server/src/generated/protocol.dart';

// here we are declaring global function to generate content using Gemini API,
// so that we can use it in tests and mocking it easily, since we cannot
// use (Mock) the GenerativeModel class directly in the tests due to the
// GenerativeModel being final.
// and we are using @visibleForTesting annotation (from meta package)to indicate
// and warn that this function is only to be used in this file and/or for
// testing purposes.
@visibleForTesting
var generateContentStream = (String apiKey, List<Content> prompt) async* {
  await for (final message in GenerativeModel(
    model: 'gemini-2.0-flash',
    apiKey: apiKey,
  ).generateContentStream(
    prompt,
  )) {
    if (message.text != null) {
      yield message.text!;
    }
  }
};

class RecipesEndpoint extends Endpoint {
  // here requireLogin is set to true, meaning that the user must be logged in
  // to access the endpoint methods. and it came from the Endpoint class.
  @override
  bool get requireLogin => true;

  Stream<Recipe> generateRecipeStream(Session session, String ingredients,
      [String? imagePath]) async* {
    final geminiApiKey = session.passwords['gemini'];
    if (geminiApiKey == null || geminiApiKey.isEmpty) {
      throw Exception('Gemini API key is not set in the session passwords.');
    }
    // // Initialize the GenerativeModel with the Gemini API key and model
    // final gemini =
    //     GenerativeModel(model: 'gemini-2.0-flash', apiKey: geminiApiKey);

    // create a cache key based on the ingredients
    final cacheKey = 'recipe-${ingredients.hashCode}';
    final cachedRecipe = await session.caches.local.get<Recipe>(cacheKey);
    // Check if the recipe is already cached
    if (cachedRecipe != null) {
      final userId = (await session.authenticated)?.userId;
      cachedRecipe.userId = userId;
      // Insert the recipe into the database
      // This is to ensure that the recipe is stored in the database even if it was
      // cached before.
      // This is useful for cases where the recipe was generated by a different user
      // and we want to store it in the current user's database.
      final recipeWithId = await Recipe.db.insertRow(session, cachedRecipe);

      // Log the cached recipe
      session.log('Returning cached recipe for ingredients: $ingredients');
      yield recipeWithId;
      return;
    }

    final List<Content> prompt = [];
    if (imagePath != null && imagePath.isNotEmpty) {
      final imageData = await session.storage
          .retrieveFile(storageId: 'public', path: imagePath);
      if (imageData == null) {
        throw Exception('Image not found');
      }

      prompt.add(
        Content.data(
          'image/jpeg',
          imageData.buffer.asUint8List(),
        ),
      );
      prompt.add(Content.text('''
Generate a recipe using the detected ingredients. Always put the title
of the recipe in the first line, and then the instructions. The recipe
should be easy to follow and include all necessary steps. Please provide
a detailed recipe. Only put the title in the first line, no markup.'''));
    }

    // Prepare the prompt for the recipe generation
    final textPrompt =
        'Generate a recipe using the following ingredients: $ingredients, always put the title '
        'of the recipe in the first line, and then the instructions. The recipe should be easy '
        'to follow and include all necessary steps. Please provide a detailed recipe.';

    if (prompt.isEmpty) {
      prompt.add(Content.text(textPrompt));
    }

    // final responseText = response.text;
    final responseTextStream = generateContentStream(geminiApiKey, prompt);

    final userId = (await session.authenticated)?.userId;

    Recipe recipe = Recipe(
      author: 'Gemini 2.0 flash',
      text: '',
      date: DateTime.now(),
      ingredients: ingredients,
      imagePath: imagePath,
    );

    // here we are assigning responseText to the recipe text from the stream
    // and yielding the recipe to the client as it is being generated
    await for (final responseText in responseTextStream) {
      recipe = recipe.copyWith(text: recipe.text + responseText);
      session.log('Received response stream: $responseText');
      yield recipe;
    }

    // Cache the generated recipe in the local cache
    await session.caches.local
        .put(cacheKey, recipe, lifetime: Duration(days: 1));

    // Insert the recipe into the database
    final recipeWithId =
        await Recipe.db.insertRow(session, recipe.copyWith(userId: userId));

    // Log the generated recipe
    session.log('Generated recipe for ingredients: $ingredients');

    yield recipeWithId;
  }

// an endpoint to get all recipes from the database
  Future<List<Recipe>> getRecipes(Session session) async {
    final userId = (await session.authenticated)?.userId;
    // Fetch all recipes from the database
    final recipes = await Recipe.db.find(session,
        where: (t) => t.deletedAt.equals(null) & t.userId.equals(userId),
        orderBy: (t) => t.date,
        orderDescending: true);

    // Return the list of recipes
    return recipes;
  }

  Future<void> deleteRecipe(Session session, int recipeId) async {
    final userId = (await session.authenticated)?.userId;
    // Check if the recipe with the given ID exists
    final recipe = await Recipe.db.findById(session, recipeId);
    if (recipe == null) {
      throw Exception('Recipe with id $recipeId not found.');
    }
    if (recipe.userId != userId) {
      throw Exception('You do not have permission to delete this recipe.');
    }
    // Mark the recipe as deleted by setting the deletedAt field to the current
    // date and time
    // This is a soft delete, meaning the recipe is not removed from the database,
    // but marked as deleted.
    recipe.deletedAt = DateTime.now();
    await Recipe.db.updateRow(session, recipe);
  }

  /// An endpoint to request a direct file upload description for an image.
  /// This method generates a unique path for the file using a UUID to prevent
  /// collisions and enumeration attacks. It returns a tuple containing the
  Future<(String? description, String path)> getUploadDescription(
      Session session, String filename) async {
    const Uuid uuid = Uuid();

    // Generate a unique path for the file
    // Using a uuid prevents collisions and enumeration attacks
    final path = 'uploads/${uuid.v4()}/$filename';

    final description = await session.storage.createDirectFileUploadDescription(
      storageId: 'public',
      path: path,
    );

    return (description, path);
  }

  /// An endpoint to verify if the file upload was successful
  Future<bool> verifyUpload(Session session, String path) async {
    return await session.storage.verifyDirectFileUpload(
      storageId: 'public',
      path: path,
    );
  }

  /// An endpoint to get the public URL for a file path.
  Future<String> getPublicUrlForPath(Session session, String path) async {
    final publicUrl =
        await session.storage.getPublicUrl(storageId: 'public', path: path);

    session.log('Public URL:\n$publicUrl');
    return publicUrl.toString();
  }

  Future<void> deleteImage(Session session, String path) async {
    // Delete the image from the storage
    await session.storage.deleteFile(storageId: 'public', path: path);
    session.log('Deleted image at path: $path');
  }
}
